# Generated by Django 4.2.7 on 2023-11-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='descriptions_contact',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание для контактов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_contact',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок для контактов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='about',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube'),
        ),
    ]
