# Generated by Django 4.2.7 on 2023-11-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_about_descriptions_contact_about_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('Languages', models.CharField(max_length=200, verbose_name='Языки програмирование')),
                ('client', models.CharField(max_length=255, verbose_name='Клиент')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на проект')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
