# Generated by Django 4.2.7 on 2023-12-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Блог', 'verbose_name_plural': 'Блог'},
        ),
    ]
