# Generated by Django 4.2.7 on 2023-12-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blog_image/', verbose_name='Картина'),
        ),
    ]
