# Generated by Django 4.2.7 on 2023-12-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='Languages',
            new_name='languages',
        ),
    ]
