# Generated by Django 4.2.7 on 2023-12-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_rename_languages_portfolio_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default=1, upload_to='portfolio_image/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
